films:
    path: /films
    defaults:
        _controller: App\Application\Controller\FilmsController::searchAction
    methods:  [GET]
films_popular:
    path: /films/popular
    defaults:
        _controller: App\Application\Controller\FilmsController::getPopularFilmsAction
    methods:  [GET]

films_in_theatres:
    path: /films/in-theatres
    defaults:
        _controller: App\Application\Controller\FilmsController::getFilmsInTheatresAction
    methods:  [GET]
new_films_in_platform:
    path: /films/platform/{platform}
    defaults:
        _controller: App\Application\Controller\FilmsController::getNewFilmsInPlatformAction
    methods:  [GET]
film:
    path: /films/{idFilmList}
    defaults:
        _controller: App\Application\Controller\FilmsController::getFilmAction
    methods:  [GET]
