services:
    App\Infrastructure\Component\Elasticsearch\ElasticsearchClientFactory:
        class: App\Infrastructure\Component\Elasticsearch\ElasticsearchClientFactory

    ElasticsearchClient:
        class: Elasticsearch\Client
        factory: ['@App\Infrastructure\Component\Elasticsearch\ElasticsearchClientFactory', createClient]
        arguments:
            - '%elasticsearch_hosts%'

    App\Infrastructure\Component\Elasticsearch\QueryAbstract:
        abstract: true

    App\Infrastructure\Component\Elasticsearch\SuggestionQuery:
        arguments:
            - '@ElasticsearchClient'
            - '%elasticsearch_index%'
        tags:
            - { name: logger, channel: elasticsearch_query }

    App\Infrastructure\Component\Elasticsearch\NormalQuery:
        arguments:
            - '@ElasticsearchClient'
            - '%elasticsearch_index%'
        tags:
            - { name: logger, channel: elasticsearch_query }
