services:
    Component.Elasticsearch.ElasticsearchClientFactory:
        class: Component\Elasticsearch\ElasticsearchClientFactory

    ElasticsearchClient:
        class: ElasticsearchClient
        factory: [@Component.Elasticsearch.ElasticsearchClientFactory, createClient]
        arguments:
            - %elasticsearch_hosts%

    Service.Elasticsearch.ElasticsearchServiceInterface:
        class: Service\Elasticsearch\ElasticsearchService
        arguments:
            - @ElasticsearchClient
