films:
    path:     /films
    defaults: { _controller: AppBundle:Films:search }
    methods:  [GET]
films_popular:
    path:     /films/popular
    defaults: { _controller: AppBundle:Films:getPopularFilms }
    methods:  [GET]
films_in_theatres:
    path:     /films/in-theatres
    defaults: { _controller: AppBundle:Films:getFilmsInTheatres }
    methods:  [GET]
film:
    path:     /films/{idFilm}
    defaults: { _controller: AppBundle:Films:getFilm }
    requirements:
        page: '\d+'
    methods:  [GET]

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
