imports:
  - { resource: business_case.yml }
  - { resource: component.yml }

services:
##### Repositories
    Repository\RepositoryAbstract:
        abstract: true
        arguments: ['@service_container']

    Repository\Db\Film\FilmRepositoryInterface:
        class: Repository\Db\Film\FilmRepository
        parent: Repository\RepositoryAbstract

    Repository\Index\Film\FilmRepositoryInterface:
        class: Repository\Index\Film\FilmRepository
        parent: Repository\RepositoryAbstract
        public: true

##### Queries
    Query\Db\Film\GetFilms:
        parent: Component\Db\ReadSlaveQuery

    Query\Db\Film\GetFilmExtraInfo:
        parent: Component\Db\ReadSlaveQuery

    Query\Index\Film\SearchFilms:
        parent: Component\Elasticsearch\SuggestionQuery
        public: true

    Query\Index\Film\GetFilm:
        parent: Component\Elasticsearch\NormalQuery
        public: true

    Query\Index\Film\GetPopularFilms:
        parent: Component\Elasticsearch\NormalQuery
        public: true

    Query\Index\Film\GetFilmsInTheatres:
        parent: Component\Elasticsearch\NormalQuery
        public: true

    ##### Services
    Service\Elasticsearch\ElasticsearchServiceInterface:
        class: Service\Elasticsearch\ElasticsearchService
        arguments:
            - '@ElasticsearchClient'

    ##### Commands
    AppBundle\Command\IndexFilmsCommand:
        tags:
            - { name: console.command }
