imports:
  - { resource: business_case.yml }
  - { resource: component.yml }

services:
##### Repositories
    Repository.RepositoryAbstract:
        class: Repository\RepositoryAbstract
        abstract: true
        arguments: [@service_container]

    Repository.Db.Film.FilmRepositoryInterface:
        class: Repository\Db\Film\FilmRepository
        parent: Repository.RepositoryAbstract

    Repository.Index.Film.FilmRepositoryInterface:
        class: Repository\Index\Film\FilmRepository
        parent: Repository.RepositoryAbstract

##### Queries
    Query.Db.Film.GetFilms:
        class: Query\Db\Film\GetFilms
        parent: Component.Db.ReadSlaveQuery

    Query.Index.Film.SearchFilms:
        class: Query\Index\Film\SearchFilms
        parent: Component.Elasticsearch.SuggestionQuery

    Query.Index.Film.GetFilm:
        class: Query\Index\Film\GetFilm
        parent: Component.Elasticsearch.SuggestionQuery

    Query.Index.Film.GetPopularFilms:
        class: Query\Index\Film\GetPopularFilms
        parent: Component.Elasticsearch.SuggestionQuery

##### Services
    Service.Elasticsearch.ElasticsearchServiceInterface:
        class: Service\Elasticsearch\ElasticsearchService
        arguments:
            - @ElasticsearchClient
