services:
  App\Domain\Interfaces\FilmsIndexerInterface:
    class: App\Domain\Service\FilmsIndexerService
    public: true
    arguments:
      - '@App\Infrastructure\Interfaces\ElasticsearchServiceInterface'
      - '%elasticsearch_index%'
      - '%elasticsearch_type_film%'
      - '@App\Domain\Helper\StringHelper'
      - '@App\Domain\Helper\FilmImageHelper'

  App\Domain\Helper\StringHelper:
    class: App\Domain\Helper\StringHelper
    public: true

  App\Domain\Helper\FilmImageHelper:
    class: App\Domain\Helper\FilmImageHelper
    public: true
