services:
  App\Domain\Interfaces\FilmsIndexerInterface:
    class: App\Domain\Service\FilmsIndexerService
    public: true
    arguments:
      - '@App\Infrastructure\Interfaces\ElasticsearchServiceInterface'
      - '%elasticsearch_index%'
      - '@App\Domain\Helper\StringHelper'
      - '@App\Domain\Helper\FilmImageHelper'

  App\Domain\Interfaces\FilmPopulatorInterface:
    class: App\Domain\Service\FilmPopulatorService
    public: true
    arguments:
      - '@App\Infrastructure\Interfaces\FilmDatabaseRepositoryInterface'

  App\Domain\Interfaces\UserFriendsFilmsInterface:
    class: App\Domain\Service\UserFriendsFilmsService
    public: true
    arguments:
      - '@App\Infrastructure\Interfaces\UserDatabaseRepositoryInterface'
      - '@App\Infrastructure\Interfaces\FilmDatabaseRepositoryInterface'
      - '@App\Infrastructure\Interfaces\FilmIndexRepositoryInterface'

  App\Domain\Helper\StringHelper:
    class: App\Domain\Helper\StringHelper
    public: true

  App\Domain\Helper\FilmImageHelper:
    class: App\Domain\Helper\FilmImageHelper
    public: true
