films:
    path: /films
    defaults:
        _controller: App\Application\Controller\FilmsController::searchAction
    methods:  [GET]
films_popular:
    path: /films/popular
    defaults:
        _controller: App\Application\Controller\FilmsController::getPopularFilmsAction
    methods:  [GET]

films_in_theatres:
    path: /films/in-theatres
    defaults:
        _controller: App\Application\Controller\FilmsController::getFilmsInTheatresAction
    methods:  [GET]
film:
    path: /films/{idFilm}
    defaults:
        _controller: App\Application\Controller\FilmsController::getFilmAction
    requirements:
        page: '\d+'
    methods:  [GET]

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'app.swagger_ui'
        permanent: true
        keepRequestMethod: true
