films:
    resource: '../config/routes/films.yaml'

users:
    resource: '../config/routes/users.yaml'

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'app.swagger_ui'
        permanent: true
        keepRequestMethod: true
