imports:
  - { resource: parameters.yaml }
  - { resource: business_case.yaml }
  - { resource: component.yaml }
  - { resource: app_services.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Controller\:
        resource: '../src/Controller'

    App\Command\:
        resource: '../src/Command'
