imports:
  - { resource: parameters.yaml }
  - { resource: domain_services.yaml }
  - { resource: infrastructure_services.yaml }
  - { resource: component.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Application\Controller\:
        resource: '../src/Application/Controller'

    App\Application\Command\:
        resource: '../src/Application/Command'
