services:
    Component.Elasticsearch.ElasticsearchClientFactory:
        class: Component\Elasticsearch\ElasticsearchClientFactory

    ElasticsearchClient:
        class: ElasticsearchClient
        factory: [@Component.Elasticsearch.ElasticsearchClientFactory, createClient]
        arguments:
            - %elasticsearch_hosts%

    Component.Elasticsearch.Query:
        class: Component\Elasticsearch\Query
        arguments:
            - @ElasticsearchClient
            - %elasticsearch_index%
        tags:
            - { name: logger, channel: elasticsearch_query }
