services:
    Component.Elasticsearch.ElasticsearchClientFactory:
        class: Component\Elasticsearch\ElasticsearchClientFactory

    ElasticsearchClient:
        class: ElasticsearchClient
        factory: [@Component.Elasticsearch.ElasticsearchClientFactory, createClient]
        arguments:
            - %elasticsearch_hosts%

    Component.Elasticsearch.QueryAbstract:
        class: Component\Elasticsearch\QueryAbstract
        abstract: true

    Component.Elasticsearch.SuggestionQuery:
        class: Component\Elasticsearch\SuggestionQuery
        arguments:
            - @ElasticsearchClient
            - %elasticsearch_index%
        tags:
            - { name: logger, channel: elasticsearch_query }
