services:
    Component\Elasticsearch\ElasticsearchClientFactory:
        class: Component\Elasticsearch\ElasticsearchClientFactory

    ElasticsearchClient:
        class: Elasticsearch\Client
        factory: ['@Component\Elasticsearch\ElasticsearchClientFactory', createClient]
        arguments:
            - '%elasticsearch_hosts%'

    Component\Elasticsearch\QueryAbstract:
        abstract: true

    Component\Elasticsearch\SuggestionQuery:
        arguments:
            - '@ElasticsearchClient'
            - '%elasticsearch_index%'
        tags:
            - { name: logger, channel: elasticsearch_query }

    Component\Elasticsearch\NormalQuery:
        arguments:
            - '@ElasticsearchClient'
            - '%elasticsearch_index%'
        tags:
            - { name: logger, channel: elasticsearch_query }
