nelmio_api_doc:
    documentation:
        info:
            title: Filmaffin API
            description:
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/films
            - ^/users
